name: 'doc-gen4'
description: 'Generate Lean 4 documentation'
author: 'Xubai Wang <self@xubai.wang>'
inputs:
  root-url:
    description: 'The root url'
    required: true
  modules:
    description: 'Modules to generate doc'
    required: true
  dir:
    description: 'Directory of the repo'
    required: false
    default: '.'
  doc-gen4-repo:
    description: 'Repository of the doc-gen4'
    required: false
    default: 'https://github.com/leanprover/doc-gen4.git'
  doc-gen4-checkout:
    description: 'Checkou point of the doc-gen4'
    required: false
    default: 'main'
runs:
  using: "composite"
  steps:
    - name: Install Elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:nightly
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install DocGen4
      run: |
        git clone ${{ inputs.doc-gen4-repo }} doc-gen4
        cd doc-gen4
        git checkout ${{ inputs.doc-gen4-checkout }}
        lake build
        cd ..
      shell: bash
    - name: Generate Documentation
      run: |
        cd ${{ inputs.dir }}
        ./doc-gen4/build/bin/doc-gen4 ${{ inputs.root-url }} ${{ inputs.modules }}
      shell: bash