name: 'doc-gen4'
description: 'Generate Lean 4 documentation'
author: 'Xubai Wang <self@xubai.wang>'
inputs:
  root-url:
    description: 'The root url'
    required: true
    default: '/'
  modules:
    description: 'Modules to generate doc'
    required: true
  dir:
    description: 'Directory of the repo'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Install Elan
      run: |
        curl -sSL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh > elan-init.sh
        chmod +x elan-init.sh
        ./elan-init.sh -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install DocGen4
      run: |
        git clone https://github.com/leanprover/doc-gen4.git
        cd doc-gen4
        lake build
        cd ..
      shell: bash
    - name: Generate Documentation
      run: |
        cd ${{ github.dir }}
        ./doc-gen4/build/bin/doc-gen4 ${{ github.root-url }} ${{ github.modules }}
      shell: bash